domain-controller:
    host: "localhost"
    port: 389
    base-dn: ""
    access-credentials:
      username: "CN=Administrator,CN=Users,DC=example,DC=com"
      password: "password"

kafka:
  host: "localhost"
  port: 9200
  writer-topic: "sssa-shares-topic"

rabbitmq:
  host: "localhost"
  port: 5672
  access-credentials:
    username: "guest"
    password: "guest"
  exchange-name: "sssa-channel-exchange"
  queue-name: "sssa-message-queue"


