domain-controller:
    host: "localhost"
    port: 389
    base-dn: ""
    access-credentials:
      username: "cn=admin,dc=mzomi,dc=mgl"
      password: "password"

rabbitmq:
  host: "localhost"
  port: 5672
  access-credentials:
    username: "guest"
    password: "guest"
  exchange-name: "sssa-channel-exchange"
  queue-name: "sssa-message-queue"


